---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: setting up security group
      ec2_group:
        name: Aws_Security_Group
        description: Rulles allowing traffic on port 22 and 80
        region: us-east-1
        rules:
         - proto: tcp
           from_port: 22
           to_port: 22
           cidr_ip: 0.0.0.0/0
         - proto: tcp
           from_port: 80
           to_port: 80
           cidr_ip: 0.0.0.0/0
         - proto: tcp
           from_port: 443
           to_port: 443
           cidr_ip: 0.0.0.0/0
        rules_egress:
         - proto: all
           cidr_ip: 0.0.0.0/0
         
 
    - name: Provision a Ec2 Instance
      ec2:
         key_name: own_ansible
         region: us-east-1
         instance_type: t2.micro
         image: ami-26ebbc5c
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags:
            Name: testserver
            Owner: owner
         monitoring: no
         vpc_subnet_id: subnet-0998fc6d
         assign_public_ip: yes
         group: Aws_Security_Group

      register: ec2_out

    - name: wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2_out.instances}}'

